modLoader = "javafml"
loaderVersion = "[43,)"
license = "Custom"

[[mods]]
modId = "applewood"
version = "${version}"
displayName = "[Let's Do] AppleWood"
authors = "berksire, KalWantsPizza&Waffles, satisfy"
icon = "pack.png"
description = '''
Vinery has Apple Logs - but have you ever wondered what the wood might look like? Here you'll find out!
'''

[[dependencies.applewood]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.applewood]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.applewood]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.applewood]]
modId = "vinery"
mandatory = true
versionRange = "[1.4.36,)"
ordering = "AFTER"
side = "BOTH"
